version: "3"
services:

  teampass-web:
    build: .
    image: teampass/teampass
    restart: unless-stopped
    environment:
      VIRTUAL_PORT: teampass.test
    ports:
    - 127.0.0.1:80:80        
    volumes:
      - ./teampass-html:/var/www/html
  
  db:
    image: mysql/mysql-server:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: teampass
      MYSQL_PASSWORD: teampass
      MYSQL_USER: teampass
    ports:
    - 127.0.0.1:3306:3306        
    volumes:
      - ./database-db:/var/lib/mysql